# Generated by Django 4.1.2 on 2022-10-31 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='name should contains only lowercase letters except the first one must be uppercase', regex='^[A-Z][a-z]+$')])),
                ('lastname', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='name should contains only lowercase letters except the first one must be uppercase', regex='^[A-Z][a-z]+$')])),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
