# Generated by Django 4.1.2 on 2022-10-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_alter_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
